<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SystemTools.ApiContracts\SystemTools.ApiContracts.csproj" />
      <ProjectReference Include="..\SystemTools.SystemToolsShared\SystemTools.SystemToolsShared.csproj" />
    </ItemGroup>

</Project>